name: medease
description: A smart healthcare companion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.15.0

  camera: ^0.10.0
  image_picker: ^0.8.7
  google_mlkit_text_recognition: ^0.4.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  share_plus: ^6.3.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
