name: medease
description: A smart healthcare companion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

path_provider: ^2.1.2

dependencies:
  flutter:
    sdk: flutter
  win32: ^3.1.4
  image_picker: ^0.8.7
  # share_plus: ^6.3.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
#  firebase_remote_config: ^5.1.0
  firebase_core: ^3.13.0
  intl: ^0.19.0
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.0+1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
#  cloud_firestore: ^5.4.0
#  firebase_storage: ^12.2.0
#  firebase_messaging: ^15.1.0
#  firebase_crashlytics: ^4.1.0
#  firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
