// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITFtb8nbvt6rvu60UkV-ggCqxlq8Pb2Q',
    appId: '1:938401449489:web:86203f4d6b2ec3c04053b0',
    messagingSenderId: '938401449489',
    projectId: 'medeaseapp-d0d47',
    authDomain: 'medeaseapp-d0d47.firebaseapp.com',
    storageBucket: 'medeaseapp-d0d47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1rUi6nPIrhYSSt-urF9P3kRLmP6wJWU',
    appId: '1:938401449489:android:8ca405ed5481b4f84053b0',
    messagingSenderId: '938401449489',
    projectId: 'medeaseapp-d0d47',
    storageBucket: 'medeaseapp-d0d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz1Px23lXYw3ynDRQ8no334v44Kgx30rE',
    appId: '1:938401449489:ios:05f2a36baa1805f84053b0',
    messagingSenderId: '938401449489',
    projectId: 'medeaseapp-d0d47',
    storageBucket: 'medeaseapp-d0d47.firebasestorage.app',
    iosBundleId: 'com.example.medeaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz1Px23lXYw3ynDRQ8no334v44Kgx30rE',
    appId: '1:938401449489:ios:05f2a36baa1805f84053b0',
    messagingSenderId: '938401449489',
    projectId: 'medeaseapp-d0d47',
    storageBucket: 'medeaseapp-d0d47.firebasestorage.app',
    iosBundleId: 'com.example.medeaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITFtb8nbvt6rvu60UkV-ggCqxlq8Pb2Q',
    appId: '1:938401449489:web:d97e8a8888a830404053b0',
    messagingSenderId: '938401449489',
    projectId: 'medeaseapp-d0d47',
    authDomain: 'medeaseapp-d0d47.firebaseapp.com',
    storageBucket: 'medeaseapp-d0d47.firebasestorage.app',
  );
} 